{'baseline':
	[LogisticRegression(C=1, solver='lbfgs', multi_class='multinomial'),
        LogisticRegression(C=10, solver='lbfgs', multi_class='multinomial'),
        LogisticRegression(C=.1, solver='lbfgs', multi_class='multinomial'),
        RandomForestClassifier(max_features=None, n_estimators=100),
        RandomForestClassifier(max_features='sqrt', n_estimators=100),
        RandomForestClassifier(max_features='log2', n_estimators=100),
        SVC(C=1, gamma=0.03, kernel='rbf'),
        SVC(C=1, gamma='scale', kernel='rbf'),
        HistGradientBoostingClassifier()
        ],

'mixed': [HistGradientBoostingClassifier(l2_regularization=1e-06, learning_rate=0.1,
                               loss='auto', max_bins=256, max_depth=None,
                               max_iter=200, max_leaf_nodes=128,
                               min_samples_leaf=50, n_iter_no_change=None,
                               random_state=23617, scoring=None, tol=1e-07,
                               validation_fraction=0.2, verbose=0),

SVC(C=52.368035023140784, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.008051730038808798,
    kernel='rbf', max_iter=-1, probability=True, random_state=1, shrinking=True,
    tol=0.001, verbose=False),

HistGradientBoostingClassifier(l2_regularization=10.0, learning_rate=0.1,
                               loss='auto', max_bins=256, max_depth=15,
                               max_iter=200, max_leaf_nodes=64,
                               min_samples_leaf=1, n_iter_no_change=None,
                               random_state=18644, scoring=None, tol=1e-07,
                               validation_fraction=0.2, verbose=0),

SVC(C=1.799125831143992, cache_size=200, class_weight=None,
    coef0=0.7926565732345652, decision_function_shape='ovr', degree=3,
    gamma=0.01858955180141993, kernel='poly', max_iter=-1, probability=True,
    random_state=1, shrinking=True, tol=0.001, verbose=False),

HistGradientBoostingClassifier(l2_regularization=0.001, learning_rate=0.1,
                               loss='auto', max_bins=256, max_depth=18,
                               max_iter=450, max_leaf_nodes=64,
                               min_samples_leaf=9, n_iter_no_change=None,
                               random_state=38742, scoring=None, tol=1e-07,
                               validation_fraction=0.1, verbose=0),

SVC(C=2854.2115055717222, cache_size=200, class_weight=None,
    coef0=0.9097801350305286, decision_function_shape='ovr', degree=2,
    gamma=0.0594124208513135, kernel='rbf', max_iter=-1, probability=True,
    random_state=1, shrinking=True, tol=0.001, verbose=False),

HistGradientBoostingClassifier(l2_regularization=100.0, learning_rate=0.1,
                               loss='auto', max_bins=256, max_depth=17,
                               max_iter=200, max_leaf_nodes=128,
                               min_samples_leaf=37, n_iter_no_change=None,
                               random_state=38160, scoring=None, tol=1e-07,
                               validation_fraction=0.2, verbose=0),

SVC(C=0.19056746772632044, cache_size=200, class_weight=None,
    coef0=0.3565163593285343, decision_function_shape='ovr', degree=5,
    gamma=0.015503770572916192, kernel='sigmoid', max_iter=-1, probability=True,
    random_state=1, shrinking=True, tol=0.001, verbose=False),

HistGradientBoostingClassifier(l2_regularization=1e-05, learning_rate=0.1,
                               loss='auto', max_bins=32, max_depth=10,
                               max_iter=350, max_leaf_nodes=8,
                               min_samples_leaf=2, n_iter_no_change=None,
                               random_state=65502, scoring=None, tol=1e-07,
                               validation_fraction=0.2, verbose=0),

SVC(C=128.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.03125, kernel='rbf',
    max_iter=-1, probability=True, random_state=1, shrinking=True, tol=0.001,
    verbose=False),

HistGradientBoostingClassifier(l2_regularization=1.0, learning_rate=0.1,
                               loss='auto', max_bins=64, max_depth=18,
                               max_iter=350, max_leaf_nodes=32,
                               min_samples_leaf=7, n_iter_no_change=None,
                               random_state=27939, scoring=None, tol=1e-07,
                               validation_fraction=0.2, verbose=0),

SVC(C=4297.397059178814, cache_size=200, class_weight=None,
    coef0=0.013499300518863278, decision_function_shape='ovr', degree=5,
    gamma=0.1820082271280914, kernel='rbf', max_iter=-1, probability=True,
    random_state=1, shrinking=True, tol=0.001, verbose=False),

HistGradientBoostingClassifier(l2_regularization=1e-10, learning_rate=0.01,
                               loss='auto', max_bins=64, max_depth=6,
                               max_iter=500, max_leaf_nodes=4,
                               min_samples_leaf=19, n_iter_no_change=None,
                               random_state=53381, scoring=None, tol=1e-07,
                               validation_fraction=0.2, verbose=0),

HistGradientBoostingClassifier(l2_regularization=10.0, learning_rate=0.1,
                               loss='auto', max_bins=32, max_depth=11,
                               max_iter=50, max_leaf_nodes=64,
                               min_samples_leaf=1, n_iter_no_change=None,
                               random_state=32899, scoring=None, tol=1e-07,
                               validation_fraction=0.1, verbose=0),

HistGradientBoostingClassifier(l2_regularization=0.01, learning_rate=0.1,
                               loss='auto', max_bins=256, max_depth=5,
                               max_iter=350, max_leaf_nodes=8,
                               min_samples_leaf=4, n_iter_no_change=None,
                               random_state=22369, scoring=None, tol=1e-07,
                               validation_fraction=0.1, verbose=0),

HistGradientBoostingClassifier(l2_regularization=1.0, learning_rate=0.1,
                               loss='auto', max_bins=256, max_depth=10,
                               max_iter=450, max_leaf_nodes=64,
                               min_samples_leaf=12, n_iter_no_change=None,
                               random_state=59156, scoring=None, tol=1e-07,
                               validation_fraction=0.2, verbose=0),

SVC(C=0.6924057373577415, cache_size=200, class_weight=None,
    coef0=0.46594279667222027, decision_function_shape='ovr', degree=2,
    gamma=0.027501589087229522, kernel='poly', max_iter=-1, probability=True,
    random_state=1, shrinking=True, tol=0.001, verbose=False),

HistGradientBoostingClassifier(l2_regularization=0.001, learning_rate=0.1,
                               loss='auto', max_bins=64, max_depth=14,
                               max_iter=200, max_leaf_nodes=16,
                               min_samples_leaf=3, n_iter_no_change=None,
                               random_state=45374, scoring=None, tol=1e-07,
                               validation_fraction=0.1, verbose=0),

SVC(C=100000.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.00194197897644,
    kernel='rbf', max_iter=-1, probability=True, random_state=1, shrinking=True,
    tol=0.001, verbose=False),

SVC(C=0.12779439580461893, cache_size=200, class_weight=None,
    coef0=-0.007860547843195675, decision_function_shape='ovr', degree=2,
    gamma=0.011489094638370643, kernel='sigmoid', max_iter=-1, probability=True,
    random_state=1, shrinking=True, tol=0.001, verbose=False),

HistGradientBoostingClassifier(l2_regularization=0.0001, learning_rate=0.1,
                               loss='auto', max_bins=128, max_depth=20,
                               max_iter=500, max_leaf_nodes=128,
                               min_samples_leaf=3, n_iter_no_change=None,
                               random_state=22006, scoring=None, tol=1e-07,
                               validation_fraction=0.2, verbose=0),

HistGradientBoostingClassifier(l2_regularization=1e-10, learning_rate=0.1,
                               loss='auto', max_bins=128, max_depth=None,
                               max_iter=500, max_leaf_nodes=8,
                               min_samples_leaf=21, n_iter_no_change=None,
                               random_state=40872, scoring=None, tol=1e-07,
                               validation_fraction=0.2, verbose=0),

HistGradientBoostingClassifier(l2_regularization=0.001, learning_rate=0.01,
                               loss='auto', max_bins=64, max_depth=9,
                               max_iter=450, max_leaf_nodes=32,
                               min_samples_leaf=12, n_iter_no_change=None,
                               random_state=26193, scoring=None, tol=1e-07,
                               validation_fraction=0.2, verbose=0),

HistGradientBoostingClassifier(l2_regularization=0.01, learning_rate=0.1,
                               loss='auto', max_bins=128, max_depth=16,
                               max_iter=200, max_leaf_nodes=32,
                               min_samples_leaf=16, n_iter_no_change=None,
                               random_state=43982, scoring=None, tol=1e-07,
                               validation_fraction=0.1, verbose=0),

HistGradientBoostingClassifier(l2_regularization=1e-09, learning_rate=0.01,
                               loss='auto', max_bins=64, max_depth=None,
                               max_iter=450, max_leaf_nodes=4,
                               min_samples_leaf=3, n_iter_no_change=None,
                               random_state=24133, scoring=None, tol=1e-07,
                               validation_fraction=0.2, verbose=0),

HistGradientBoostingClassifier(l2_regularization=10.0, learning_rate=0.1,
                               loss='auto', max_bins=256, max_depth=20,
                               max_iter=400, max_leaf_nodes=64,
                               min_samples_leaf=5, n_iter_no_change=None,
                               random_state=18316, scoring=None, tol=1e-07,
                               validation_fraction=0.2, verbose=0),

HistGradientBoostingClassifier(l2_regularization=1e-06, learning_rate=0.1,
                               loss='auto', max_bins=128, max_depth=12,
                               max_iter=300, max_leaf_nodes=4,
                               min_samples_leaf=3, n_iter_no_change=None,
                               random_state=28019, scoring=None, tol=1e-07,
                               validation_fraction=0.2, verbose=0),

HistGradientBoostingClassifier(l2_regularization=1e-05, learning_rate=0.1,
                               loss='auto', max_bins=16, max_depth=None,
                               max_iter=400, max_leaf_nodes=128,
                               min_samples_leaf=48, n_iter_no_change=None,
                               random_state=2136, scoring=None, tol=1e-07,
                               validation_fraction=0.2, verbose=0),

SVC(C=9366.20074943413, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0015583202500353984,
    kernel='rbf', max_iter=-1, probability=True, random_state=1, shrinking=True,
    tol=0.001, verbose=False),

HistGradientBoostingClassifier(l2_regularization=1e-09, learning_rate=0.1,
                               loss='auto', max_bins=8, max_depth=7,
                               max_iter=150, max_leaf_nodes=128,
                               min_samples_leaf=27, n_iter_no_change=None,
                               random_state=9274, scoring=None, tol=1e-07,
                               validation_fraction=0.1, verbose=0),

HistGradientBoostingClassifier(l2_regularization=1e-06, learning_rate=0.1,
                               loss='auto', max_bins=256, max_depth=15,
                               max_iter=350, max_leaf_nodes=8,
                               min_samples_leaf=20, n_iter_no_change=None,
                               random_state=32084, scoring=None, tol=1e-07,
                               validation_fraction=0.1, verbose=0),

HistGradientBoostingClassifier(l2_regularization=0.1, learning_rate=0.01,
                               loss='auto', max_bins=4, max_depth=18,
                               max_iter=200, max_leaf_nodes=4,
                               min_samples_leaf=39, n_iter_no_change=None,
                               random_state=15428, scoring=None, tol=1e-07,
                               validation_fraction=0.1, verbose=0)
}



